pipeline {
  agent any

  environment {
    WOKING_DIR = "services/${params.APP_NAME}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: "${params.BRANCH_NAME}"]],
          userRemoteConfigs: [[url: 'https://github.com/howseman/jenkins-pipelines.git']]]
        )
      }
    }
    stage('Build') {
      steps {
        dir(env.WOKING_DIR) {
          sh 'ls -al'
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }
  }
}
