pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout([
          $class: 'GitSCM',
          branches: [[name: "${params.BRANCH_NAME}"]],
          userRemoteConfigs: [[url: 'https://github.com/howseman/jenkins-pipelines.git']]]
        )
      }
    }
    stage('Build') {
      steps {
        dir("services/${params.APP_NAME}") {
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }
  }
}
