pipeline {
  agent any
  parameters {
    string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'The branch to be built')
  }
  stages {
    stage('Build') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: "${params.BRANCH_NAME}"]], userRemoteConfigs: [[url: 'https://github.com/your/repo']]])
        sh 'npm install'
        sh 'npm run build'
      }
    }
  }
}
